# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.IntegerField()),
                ('actorIDs', models.CharField(max_length=200)),
                ('directorID', models.IntegerField()),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('actorScore', models.FloatField()),
                ('directorScore', models.FloatField()),
                ('lengthScore', models.FloatField()),
                ('genreScore', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.MovieInfo')),
            ],
        ),
    ]
