# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_auto_20161125_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sex_is_male', models.BooleanField()),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('type_is_director', models.BooleanField()),
            ],
        ),
    ]
