# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='num_of_movies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
