# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_person_num_of_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreloadPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='aggregateinfo',
            old_name='length_score',
            new_name='duration_score',
        ),
        migrations.RenameField(
            model_name='movieinfo',
            old_name='length',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='moviescore',
            old_name='length_score',
            new_name='duration_score',
        ),
    ]
