# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0005_auto_20161203_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='preloadperson',
            name='type',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
