# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0008_auto_20161204_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregateinfo',
            old_name='actor_score',
            new_name='director_genre_score',
        ),
        migrations.RemoveField(
            model_name='moviescore',
            name='actors_correlation_score',
        ),
        migrations.AddField(
            model_name='aggregateinfo',
            name='first_actor_director_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateinfo',
            name='first_actor_genre_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateinfo',
            name='first_actor_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateinfo',
            name='second_actor_director_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateinfo',
            name='second_actor_genre_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregateinfo',
            name='second_actor_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
